version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    ports:
      - "1234:1234"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - app-network

  frontend:
    build:
      context: ./View
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:1234
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
